
#
# This LookML file was generated by AtScale on 2021-09-22T18:27:16.970774Z
#
# AtScale engine version: 2021.3.0.10827
# AtScale DesignCenter version: 2021.3.0.17972
# AtScale version: 2021.3.0.3872
# Organization: default
# Project: 2020AdventureWorksDW2012

connection: "bitool1"
label: "2020AdventureWorksDW2012"


include: "/views/2020AdventureWorksDW2012/ASAdventureSmall.view.lkml"


explore: ASAdventureSmall {
  label: "ASAdventureSmall"
}
